Add support for aria-disabled attribute
testing-library/jest-dom pull request #302
Opened 2020-10-22 19:40 UTC by rlaffers

**What**:

Adding support for [aria-disabled](https://www.w3.org/TR/wai-aria-1.1/#aria-disabled) attribute in `toBeDisabled` and `toBeEnabled` matchers.

**Why**:

`aria-disabled` is a standard attribute with semantics similar to the `disabled` attribute. Until now, this attribute has been ignored by `toBeDisabled` and `toBeEnabled` matchers.

**How**:

By extending `toBeDisabled` and `toBeEnabled` matchers.

**Checklist**:

- [x] Documentation
- [x] Tests
- [ ] Updated Type Definitions **N/A**
- [x] Ready to be merged

2020-10-22 21:18 UTC, eps1lon requested changes
This was discussed at length in https://github.com/testing-library/jest-dom/issues/144. Could you continue the discussion there? If you want to propose an implementation please address all the points raised in #144.

2020-10-22 22:05 UTC, gnapse commented
I'll add a note in the README to the documentation of these matchers.

2020-10-22 22:11 UTC, gnapse commented
Please check #303.

2020-10-23 11:17 UTC, rlaffers commented
Thanks for pointing out the discussion in #144 . (I had not come across it although I searched for issues mentioning `toBeDisabled`; only open issues though). The reasoning for not adding this to `toBeDisabled` is sound and I agree with it. I'm closing this PR.

2020-10-23 11:18 UTC, closed without merging