Update missing documentation in README
testing-library/jest-dom pull request #356
Opened 2021-04-20 17:21 UTC by kylejw2

This PR is linked to this issue I created https://github.com/testing-library/jest-dom/issues/355.

When following the documentation before these updates, there's a strong change the user will encounter an error because the `extend-expect` module hasn't been imported. This PR includes the missing documentation and should help users avoid this error or easily troubleshoot it.

2021-04-20 22:52 UTC, gnapse requested changes
Importing the package's root module will already do what `extend-expect` used to do. That is, importing this:

```js
// In your own jest-setup.js (or any other name)
import '@testing-library/jest-dom'
```

is already enough. We haven't removed `extend-expect`, but I was planning to make a new major release soon with this and at least one other breaking change.

Can you comment why you think you need to import this in addition to already being importing `@testing-library/jest-dom`? Maybe I'm missing something.

2021-04-21 16:23 UTC, kylejw2 commented
I assumed that only having the following would work, given the documentation.
```typescript
// In your own jest-setup.js (or any other name)
import '@testing-library/jest-dom'
```
Correct me if I'm wrong please, but importing `jest-dom` through the above approach only pulls in the `index` file of the `jest-dom` folder. Perhaps it didn't work as expected for me because I couldn't find an `index` file in the `jest-dom` folder.
![Screen Shot 2021-04-21 at 10 19 58 AM](https://user-images.githubusercontent.com/66093447/115587900-6dba1e80-a28b-11eb-93d4-daaf13750499.png)
Here's the file/folder structure I have from installing the `jest-dom` library. There's no `index` file so I had to directly import `extend-expect` in order to access its methods.

2021-04-21 19:53 UTC, gnapse commented
The index file lives inside the `dist` folder, and it is considered the main entry point when importing the package thanks to [this line](https://github.com/testing-library/jest-dom/blob/21ad89bc707b6e41af887d1bd103dd6dbc665dee/package.json#L5) in the `package.json` file.

What version of jest-dom are you using when you get this behaviour of the regular package import not working properly?

2021-04-22 22:19 UTC, kylejw2 commented
I think you may have located the issue. I'm using version 4.2.4

2021-04-23 01:51 UTC, gnapse commented
Yup, that's what I thought. I'm going to close this for now.

2021-04-23 01:51 UTC, closed without merging