feat(toHaveValue): Asserting aria-valuenow
testing-library/jest-dom pull request #479
Opened 2022-09-20 17:51 UTC by idanen

Resolves #478

**What**:

Change `.toHaveValue()` to support `aria-valuenow`

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Updated Type Definitions
- [ ] Ready to be merged

2022-09-20 17:51 UTC, idanen commented
How do I update documentation?

2022-09-21 12:24 UTC, waynevanson requested changes

2022-09-21 13:30 UTC, idanen commented on src/utils.js
> +      return element.value ?? accessibleValue
`value` should take precedence.
That's how Chrome's accessibility tab behaves

2022-09-22 10:07 UTC, waynevanson approved these changes

2022-09-23 10:02 UTC, idanen commented
@gnapse @nickmccurdy any chance one of you can help push this forward?

2024-08-05 15:04 UTC, gnapse approved these changes
Only one comment that I think needs to be addressed before merging this.

2024-08-05 15:04 UTC, gnapse commented on src/utils.js
> +}
To avoid the eslint issue, maybe you can `return undefined` inside the `if` statement.

2024-08-19 08:26 UTC, idanen commented
@gnapse finally fixed the coverage. Can you please give it another look?

2024-08-23 19:43 UTC, merged

2024-08-23 19:44 UTC, gnapse commented
@all-contributors please add @idanen for code, test

2024-08-23 19:44 UTC, gnapse commented
@all-contributors please add @waynevanson for code, test

2024-08-23 19:45 UTC, gnapse commented
https://github.com/all-contributors please add @waynevanson for code, test

2024-08-23 19:46 UTC, gnapse commented
@all-contributors please add @waynevanson for code, test

2024-08-23 19:49 UTC, gnapse commented
@all-contributors please add @idanen for code, test