fix: proper @jest/globals import
testing-library/jest-dom pull request #530
Opened 2023-08-28 14:34 UTC by jgoz

**What**:

Change import from `@jest/globals` to use direct import instead of default import.

**Why**:

Fixes #529.

`@jest/globals` does not have a default export, so in environments that do not use synthetic default import logic, either `import {expect}` or `import * as globals` is needed. I chose the former.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Updated Type Definitions
- [x] Ready to be merged

2023-08-29 14:38 UTC, jgoz commented
@nickmccurdy one more fix to the ESM stuff

2023-09-05 06:58 UTC, nickmccurdy commented
Now getting this error when I import the patched package with Jest:
```
ReferenceError: expect is not defined

  10 | import 'aria-query';
  11 |
> 12 | expect.extend(extensions);
     | ^
  13 |

  at ../../Repos/jest-dom/dist/index.mjs:12:1
```

2023-09-05 06:59 UTC, nickmccurdy requested changes
Now getting this error when I import the patched package with Jest:
```
ReferenceError: expect is not defined

  10 | import 'aria-query';
  11 |
> 12 | expect.extend(extensions);
     | ^
  13 |

  at ../../Repos/jest-dom/dist/index.mjs:12:1
```

2023-09-05 15:41 UTC, jgoz commented
@nickmccurdy I only changed the `jest-globals` entry point which wouldn't have affected `index.mjs`. Can you ensure that you're importing `@testing-library/jest-dom/jest-globals`?

2023-09-05 20:29 UTC, nickmccurdy commented
I was importing the root entry, but I get a very similar error about accessing properties from `undefined` if I import `/jest-globals`. I'm not at my dev machine so I'm writing this from memory, but I can update my comment with the exact error as soon as I log on.

2023-09-05 23:13 UTC, nickmccurdy commented
I just realized I've been using `setupFiles` instead of `setupFilesAfterEnv`, my mistake! I'll double check and merge if this is working.

2023-09-06 02:52 UTC, nickmccurdy approved these changes

2023-09-06 02:53 UTC, merged