fix: proper vitest ts support (#515)
testing-library/jest-dom pull request #589
Opened 2024-03-11 15:35 UTC by nyaapass

**What**:

This PR [extends Vitest's default `Assertion` interface](https://vitest.dev/guide/extending-matchers.html#:~:text=If%20you%20are%20using%20TypeScript%2C%20since%20Vitest%200.31.0%20you%20can%20extend%20default%20Assertion%20interface%20in%20an%20ambient%20declaration%20file%20(e.g%3A%20vitest.d.ts)%20with%20the%20code%20below%3A) to fix the `toBeInTheDocument` ts error when using Vitest (#515).

**Why**:

I don't know. But [from this comment](https://github.com/testing-library/jest-dom/issues/515#issuecomment-1987823474), adding `<reference types="@testing-library/jest-dom" />` in custom `vitest-setup.ts` file would fix this error. Therefore I think the `types/vitest.d.ts` may need to be updated.

And when I install this repo's dependencies by pnpm and running `tsc -p types/__tests__/vitest`, there would be similar errors of #515 (if using npm, there would be no error). This PR would fix this error even using pnpm.

<img width="2032" alt="image" src="https://github.com/testing-library/jest-dom/assets/13141973/dadf9ca9-afac-42e6-807f-ba0c09b9b7df">

**How**:

https://vitest.dev/guide/extending-matchers.html

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Updated Type Definitions
- [x] Ready to be merged

2024-03-12 01:42 UTC, ecoms-ye commented
Confirmed in my office computer (a pnpm monorepo with the [With Vitest](https://github.com/testing-library/jest-dom?tab=readme-ov-file#with-vitest) and [With TypeScript](https://github.com/testing-library/jest-dom?tab=readme-ov-file#with-typescript) setup): 

- Switch to the fork version by changing `package.json` to `"@testing-library/jest-dom": "https://github.com/nyaapass/jest-dom"`, the error can be fixed:
    - <img width="924" alt="image" src="https://github.com/testing-library/jest-dom/assets/117143128/c7fea1e5-9058-434a-be15-53cd845517a3">
- When back to the original `@testing-library/jest-dom@6.4.2` version, the #515 error would be shown again: 
    - <img width="907" alt="image" src="https://github.com/testing-library/jest-dom/assets/117143128/8d7d2f3f-b13a-4b56-8877-92e3bacaf144">

2024-08-21 07:34 UTC, Dalcvi commented
What is the reason that this change is not being merged in? Vitest removed `@vitest/expect` interface, so when `@testing-library/jest-dom/vitest` is trying to extend `@vitest/expect` interface, it just does nothing. By the way I see it, this change actually corrects the way you are expected to extend the interface since 0.x.x version, so what is the hold up here?

2024-08-21 07:36 UTC, Dalcvi requested changes

2024-08-21 07:36 UTC, Dalcvi commented on types/vitest.d.ts
> +  type AsymmetricMatchersContaining,
These two are unused.

You actually type out the name but don't use it in the line 14 and 19.

2024-08-21 07:38 UTC, Dalcvi commented
> What is the reason that this change is not being merged in? Vitest removed `@vitest/expect` interface, so when `@testing-library/jest-dom/vitest` is trying to extend `@vitest/expect` interface, it just does nothing. By the way I see it, this change actually corrects the way you are expected to extend the interface since 0.x.x version, so what is the hold up here?

Alright, other PR was changed with these changes https://github.com/testing-library/jest-dom/commit/06d19ba759a5ff4b51417cc9a7ecb72c785eb74d waiting for release I guess

2024-08-29 00:54 UTC, gnapse commented
I guess we can close this as superseded by #612

2024-08-29 00:54 UTC, closed without merging